version: '3.2'
services:
  mysql:
    image: mysql:8.0
    container_name: zabbix_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=encrypted
      - MYSQL_USER=naveen
      - MYSQL_PASSWORD=secret
  zabbix_server:
    image: zabbix/zabbix-server-mysql:ubuntu-latest
    container_name: zabbix_server_mysql
    ports:
    - 10051:10051
    depends_on:
    - mysql
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=encrypted
      - DB_SERVER_HOST=zabbix_mysql
  web_interface:
    image: zabbix/zabbix-web-apache-mysql:ubuntu-latest
    container_name: zabbix_web_apache_mysql
    ports:
    - 80:8080
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=encrypted
      - DB_SERVER_HOST=zabbix_mysql
      - ZBX_SERVER_HOST=zabbix_server_mysql
      - PHP_TZ=Asia/Kolkata
    depends_on:
      - mysql
      - zabbix_server