apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  ports:
    - port: 3306
      protocol: tcp
      targetPort: 3306
  selector:
    app: mysql-pod
  # clusterIP: None
---
apiVersion: v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replica: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-pod
    spec:
      containers:
        - image: mysql:8.0
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: encypted
            - name: MYSQL_PASSWORD
              value: secret
            - name: MYSQL_USER
              value: spongebob
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-persistent-volume-claim
